// <auto-generated />
using BlazorSignalRApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorWebAppMovies.Data.Migrations.ApplicationDb
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251109173446_UserRoleLen50_AndSeed")]
    partial class UserRoleLen50_AndSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorSignalRApp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Role")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "kirk@enterprise.com",
                            Name = "James Kirk",
                            Role = "Captain"
                        },
                        new
                        {
                            Id = 2,
                            Email = "spock@enterprise.com",
                            Name = "Spock",
                            Role = "Science Officer"
                        },
                        new
                        {
                            Id = 3,
                            Email = "bones@enterprise.com",
                            Name = "Leonard McCoy",
                            Role = "Chief Medical Officer"
                        },
                        new
                        {
                            Id = 4,
                            Email = "uhura@enterprise.com",
                            Name = "Nyota Uhura",
                            Role = "Communications Officer"
                        },
                        new
                        {
                            Id = 5,
                            Email = "scotty@enterprise.com",
                            Name = "Montgomery Scott",
                            Role = "Chief Engineer"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
